[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.release]
command = "cargo"
args = ["build","--release"]
dependencies = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.bench]
command = "cargo"
args = ["bench"]
dependencies = ["release"]

[tasks.clean_paper]
command = "pwsh"
args = ["./paper/scripts/clean.ps1"]

[tasks.fig]
command = "pwsh"
args = ["./paper/scripts/make_figs.ps1"]

[tasks.paper]
command = "pdflatex"
args = ["-output-directory=./paper/builds", "-shell-escape", "./paper/src/paper.tex"]
dependencies = ["clean_paper", "fig"]

[tasks.all_build]
dependencies = ["release", "test", "paper"]

[tasks.all]
dependencies = ["release", "test", "bench", "paper"]
