[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.release]
command = "cargo"
args = ["build","--release"]
dependencies = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.bench]
command = "cargo"
args = ["bench"]
dependencies = ["release"]

[tasks.clean_paper]
command = "pwsh"
args = ["./paper/clean.ps1"]

[tasks.paper_fig_gen]
command = "pwsh"
args = ["./paper/make_figs.ps1"]

[tasks.build_paper]
command = "pdflatex"
args = ["-output-directory=./paper/builds", "-shell-escape", "./paper/src/paper.tex"]
dependencies = ["paper_fig_gen", "clean_paper"]

[tasks.all_build]
dependencies = ["release", "build_paper", "test"]

[tasks.all]
dependencies = ["release", "build_paper", "test", "bench"]
